// Mock data for live camera streams
export const _liveStreams = [
  {
    id: 'stream-1',
    roomName: 'Asosiy konferensiya xonasi',
    cameraId: 'CAM-001',
    location: 'Birinchi qavat, A blok',
    viewers: 1247,
    duration: '2:34:15',
    status: 'live' as const,
    thumbnailUrl: '/assets/illustrations/camera/room1.png',
    resolution: '1080p',
  },
  {
    id: 'stream-2',
    roomName: "Yig'ilishlar xonasi #2",
    cameraId: 'CAM-005',
    location: 'Ikkinchi qavat, B blok',
    viewers: 856,
    duration: '1:15:42',
    status: 'live' as const,
    thumbnailUrl: '/assets/illustrations/camera/room2.png',
    resolution: '4K',
  },
  {
    id: 'stream-3',
    roomName: 'Trening markazi',
    cameraId: 'CAM-012',
    location: 'Birinchi qavat, C blok',
    viewers: 2134,
    duration: '0:45:23',
    status: 'live' as const,
    thumbnailUrl: '/assets/illustrations/camera/room3.png',
    resolution: '1080p',
  },
  {
    id: 'stream-4',
    roomName: 'VIP uchrashuv xonasi',
    cameraId: 'CAM-008',
    location: 'Uchinchi qavat, Penthaus',
    viewers: 342,
    duration: '3:22:10',
    status: 'recording' as const,
    thumbnailUrl: '/assets/illustrations/camera/room4.png',
    resolution: '4K',
  },
  {
    id: 'stream-5',
    roomName: 'Ochiq ofis maydoni',
    cameraId: 'CAM-015',
    location: 'Ikkinchi qavat, Markaziy',   
    viewers: 1893,
    duration: '5:12:33',
    status: 'live' as const,
    thumbnailUrl: '/assets/illustrations/camera/room3.png',
    resolution: '1080p',
  },
  {
    id: 'stream-6',
    roomName: 'Ishlab chiqarish studiyasi',
    cameraId: 'CAM-020',
    location: "Yerto'la, Studio A",
    viewers: 567,
    duration: '0:28:45',
    status: 'live' as const,
    thumbnailUrl: '/assets/illustrations/camera/room3.png',
    resolution: '4K',
  },
  {
    id: 'stream-7',
    roomName: "Kutubxona va o'quv xonasi",
    cameraId: 'CAM-007',
    location: 'Birinchi qavat, D blok',
    viewers: 423,
    duration: '1:55:12',
    status: 'live' as const,
    thumbnailUrl: '/assets/illustrations/camera/room2.png',
    resolution: '720p',
  },
  {
    id: 'stream-8',
    roomName: 'Ijodiy loyihalar xonasi',
    cameraId: 'CAM-018',
    location: 'Ikkinchi qavat, A blok',
    viewers: 1024,
    duration: '2:10:00',
    status: 'recording' as const,
    thumbnailUrl: '/assets/illustrations/camera/room1.png',
    resolution: '1080p',
  },
];
